import type { GameCommand } from '../engine/commands'

export const MVP_DEMO_SEED = 'demo-143510'

export const MVP_DEMO_COMMANDS: readonly GameCommand[] = [
  { type: 'START_RUN' },
  { type: 'ENTER_NEXT_STAGE' },
  { type: 'SPIN_COMBAT_SLOT' },
  { type: 'TOGGLE_REEL_LOCK', reel: 'target' },
  { type: 'REROLL_UNLOCKED' },
  { type: 'TOGGLE_REEL_LOCK', reel: 'target' },
  { type: 'REROLL_UNLOCKED' },
  { type: 'CONFIRM_COMBAT_SLOT' },
  { type: 'SPIN_COMBAT_SLOT' },
  { type: 'TOGGLE_REEL_LOCK', reel: 'action' },
  { type: 'CONFIRM_COMBAT_SLOT' },
  { type: 'SPIN_COMBAT_SLOT' },
  { type: 'TOGGLE_REEL_LOCK', reel: 'action' },
  { type: 'CONFIRM_COMBAT_SLOT' },
  { type: 'CHOOSE_REWARD', reward: { kind: 'augment', id: 'combo_starter' } },
  { type: 'ENTER_NEXT_STAGE' },
  { type: 'SPIN_COMBAT_SLOT' },
  { type: 'TOGGLE_REEL_LOCK', reel: 'action' },
  { type: 'CONFIRM_COMBAT_SLOT' },
  { type: 'CHOOSE_REWARD', reward: { kind: 'item', id: 'multi_hit_charm' } },
  { type: 'ENTER_NEXT_STAGE' },
  { type: 'RESOLVE_REST', action: 'purify' },
  { type: 'ENTER_NEXT_STAGE' },
  { type: 'LEAVE_SHOP' },
  { type: 'ENTER_NEXT_STAGE' },
  { type: 'SPIN_COMBAT_SLOT' },
  { type: 'TOGGLE_REEL_LOCK', reel: 'action' },
  { type: 'CONFIRM_COMBAT_SLOT' },
  { type: 'CHOOSE_REWARD', reward: { kind: 'augment', id: 'combo_finisher' } },
  { type: 'ENTER_NEXT_STAGE' },
  { type: 'RESOLVE_EVENT', choice: 'reward' },
  { type: 'CHOOSE_REWARD', reward: { kind: 'item', id: 'ember_magazine' } },
  { type: 'ENTER_NEXT_STAGE' },
  { type: 'SPIN_COMBAT_SLOT' },
  { type: 'TOGGLE_REEL_LOCK', reel: 'action' },
  { type: 'CONFIRM_COMBAT_SLOT' },
  { type: 'CHOOSE_REWARD', reward: { kind: 'augment', id: 'debt_collector' } },
  { type: 'ENTER_NEXT_STAGE' },
  { type: 'RESOLVE_REST', action: 'heal' },
  { type: 'ENTER_NEXT_STAGE' },
  { type: 'SPIN_COMBAT_SLOT' },
  { type: 'TOGGLE_REEL_LOCK', reel: 'action' },
  { type: 'CONFIRM_COMBAT_SLOT' },
  { type: 'CHOOSE_REWARD', reward: { kind: 'item', id: 'safety_valve' } },
  { type: 'ENTER_NEXT_STAGE' },
  { type: 'BUY_SHOP_ITEM', rewardId: 'retaliation_matrix' },
  { type: 'LEAVE_SHOP' },
  { type: 'ENTER_NEXT_STAGE' },
  { type: 'SPIN_COMBAT_SLOT' },
  { type: 'TOGGLE_REEL_LOCK', reel: 'action' },
  { type: 'CONFIRM_COMBAT_SLOT' },
  { type: 'CHOOSE_REWARD', reward: { kind: 'item', id: 'mirror_buckler' } },
  { type: 'ENTER_NEXT_STAGE' },
  { type: 'RESOLVE_REST', action: 'purify' },
  { type: 'ENTER_NEXT_STAGE' },
  { type: 'SPIN_COMBAT_SLOT' },
  { type: 'TOGGLE_REEL_LOCK', reel: 'action' },
  { type: 'CONFIRM_COMBAT_SLOT' },
  { type: 'SPIN_COMBAT_SLOT' },
  { type: 'CONFIRM_COMBAT_SLOT' },
  { type: 'SPIN_COMBAT_SLOT' },
  { type: 'CONFIRM_COMBAT_SLOT' },
  { type: 'SPIN_COMBAT_SLOT' },
  { type: 'CONFIRM_COMBAT_SLOT' },
  { type: 'SPIN_COMBAT_SLOT' },
  { type: 'TOGGLE_REEL_LOCK', reel: 'action' },
  { type: 'CONFIRM_COMBAT_SLOT' },
  { type: 'CHOOSE_REWARD', reward: { kind: 'item', id: 'black_market_stamp' } },
  { type: 'ENTER_NEXT_STAGE' },
  { type: 'RESOLVE_EVENT', choice: 'rest' },
  { type: 'ENTER_NEXT_STAGE' },
  { type: 'SPIN_COMBAT_SLOT' },
  { type: 'TOGGLE_REEL_LOCK', reel: 'action' },
  { type: 'CONFIRM_COMBAT_SLOT' },
  { type: 'SPIN_COMBAT_SLOT' },
  { type: 'REROLL_UNLOCKED' },
  { type: 'CONFIRM_COMBAT_SLOT' },
  { type: 'SPIN_COMBAT_SLOT' },
  { type: 'REROLL_UNLOCKED' },
  { type: 'TOGGLE_REEL_LOCK', reel: 'action' },
  { type: 'CONFIRM_COMBAT_SLOT' },
]
